### ISSUE TITLE
[FE] Implementation of navigation (concept) 

### ISSUE THREAD

**Issue by alexfoxrussian** [ncedu-tlt/2020_ncpr_english_lessons#18]
Необходимо сделать концепт навигации по сайту (ссылки, выпадающие меню и т.д.)

**Comment by AmiliaRei** [comment]
В ходе работы над тикетом по навигации сайта была создана wiki-страница 
https://github.com/ncedu-tlt/2020_ncpr_english_lessons/wiki/Концепт-навигации-по-сайту

**Comment by AmiliaRei** [comment]
Навигация изменена
