### ISSUE TITLE
[DEV][TestDrive] Артем А. - Дизайн фронтенд для преподавателей (win forms)

### ISSUE THREAD

**Issue by dnsonin** [ncedu-tlt/2020_ncpr_english_lessons#6]
Привет Артём,

Размести пожалуйста результаты выполнения домашнего задания по проекту на нашей Wiki страничке.
Графический материал, проект(если есть) и несколько предложений с комментариями.

Спасибо.

**Comment by artyom-astafyev** [comment]
Готово - https://github.com/ncedu-tlt/2020_ncpr_english_lessons/wiki/%D0%94%D0%B8%D0%B7%D0%B0%D0%B9%D0%BD-%D1%84%D1%80%D0%BE%D0%BD%D1%82%D0%B5%D0%BD%D0%B4-%D0%B4%D0%BB%D1%8F-%D0%BF%D1%80%D0%B5%D0%BF%D0%BE%D0%B4%D0%B0%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D0%B5%D0%B9
