### ISSUE TITLE
[QA] Test Case 01

### ISSUE THREAD

**Issue by alexfoxrussian** [ncedu-tlt/2020_ncpr_english_lessons#9]
ID: TC 01 
#6
Pre-condition: Personal account design for teachers
Steps to reproduce: 
1.	Load https://github.com/ncedu-tlt/2020_ncpr_english_lessons/wiki
2.	Open the https://github.com/ncedu-tlt/2020_ncpr_english_lessons/wiki/Дизайн-фронтенд-для-преподавателей
Expected result:
The page contains graphic materials and explanations: 
•	editing personal information on the home page 
•	the ability to start a chat and create courses

ER=AR

**Comment by bernerdasha** [comment]
![image](https://user-images.githubusercontent.com/67468806/87200410-8c0ee900-c30d-11ea-8df0-f755da1c94bd.png)

**Comment by bernerdasha** [comment]
Test status: PASSED
